# Global config.
title = "Sia"
baseurl = "https://veritascoin.io/" # TODO: schemaless?
googleAnalytics = "UA-58715089-4"

# i18n and language specific config.
IsMultiLingual = true
DefaultContentLanguage = "en"
[Languages]
  [Languages.de]
    weight = 0
  [Languages.en]
    weight = 1
  [Languages.fr]
    weight = 2
  [Languages.ru]
    weight = 3
  [Languages.zh-hans]
    weight = 4
  [Languages.zh-hant]
    weight = 5
  [Languages.ha]
    weight = 6
